version: '2'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_USER=moodle_user
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_storage:/var/lib/mysql
  moodle:
    build: ./nginx/
    image: moodlenginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - moodle_data:/moodledata
      - certbot_certificates:/certs/
      - certbot_challenges:/certChallenges/
      # - /moodleTest/config.php:/var/www/html/config.php
      - moodle_config_file:/var/www/html/config.php
    depends_on:
      - mariadb
  redis:
    image: redis:latest
    restart: always
  cerbot:
    build: ./certbot/
    image: simplecertbot
    environment:
      - DOMAIN=moodle.oact.cz
      - EMAIL=davi.podeszwa@gmail.com
      - STAGING=
      - CRONS=50 * * * *
    volumes:
      - certbot_certificates:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      - moodle

# Volumes for persistent data that are mounted on filesystem
volumes:
  mariadb_storage:
  moodle_data:
  certbot_certificates:
  certbot_challenges:
  moodle_config_file:
    driver: local
    driver_opts:
      type: none
      device: /moodleTest/config.php
      o: bind
