version: '2'
services:
  mariadb:
    image: mariadb:latest
    container_name: moodle_database
    restart: always
    environment:
      - MARIADB_USER=moodle_user
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_storage:/var/lib/mysql
    ports:
      - '3309:3306'
  moodle:
    build: ./nginx/
    image: moodlenginx
    container_name: moodle_web
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /moodle_data:/moodledata
      - certbot_certificates:/certificates
      - certbot_challenges:/certificateChallenges
      - ./moodle_config.php:/var/www/html/config.php
    environment:
      - NO_CRON=1
    depends_on:
      - mariadb
      - redis
  redis:
    image: redis:latest
    container_name: moodle_redis
    restart: always
  cerbot:
    build: ./certbot/
    image: simplecertbot
    container_name: moodle_certbot
    restart: always
    environment:
      - DOMAIN=moodle.oact.cz
      - EMAIL=davi.podeszwa@gmail.com
      - STAGING=true
      - CRONS=50 * * * *
    volumes:
      - certbot_certificates:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      - moodle


# Volumes for persistent data that are mounted on filesystem
volumes:
  mariadb_storage:
  certbot_certificates:
  certbot_challenges: