[supervisord]
nodaemon=true

[program:chown-moodledata]
command=chown -R www-data:www-data /moodledata && chown -R www-data:www-data /certs
startsecs = 0
autorestart = false
startretries = 1

[program:cron]
command=cron -f
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=/bin/bash -c "php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
